version: 1
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: normal
  llm_file:
    class: logging.FileHandler
    level: DEBUG
    filename: llm.log
    formatter: llm
  ui_file:
    class: logging.FileHandler
    level: DEBUG
    filename: ui.log
    formatter: normal
formatters:
  normal:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
  llm:
    format: "%(asctime)s %(levelname)s: |%(message)s|"
loggers:
  llm:
    level: DEBUG
    handlers: [llm_file]
    propogate: no
  main:
    level: DEBUG
    handlers: [console]
  ui:
    level: DEBUG
    handlers: [ui_file]
root:
  level: INFO
