version: 1
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: normal
  api_file:
    class: logging.FileHandler
    level: DEBUG
    filename: api.log
    formatter: api
  editor_file:
    class: logging.FileHandler
    level: DEBUG
    filename: editor.log
    formatter: normal
formatters:
  normal:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
  api:
    format: "%(asctime)s |%(message)s|"
loggers:
  api:
    level: INFO
    handlers: [api_file]
    propogate: no
  main:
    level: INFO
    handlers: [console]
  langchain:
    level: DEBUG
    handlers: [api_file]
  editor:
    level: DEBUG
    handlers: [editor_file]
root:
  level: DEBUG
